/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace ContractDeployer {
  export type ForceDeploymentStruct = {
    bytecodeHash: PromiseOrValue<BytesLike>;
    newAddress: PromiseOrValue<string>;
    callConstructor: PromiseOrValue<boolean>;
    value: PromiseOrValue<BigNumberish>;
    input: PromiseOrValue<BytesLike>;
  };

  export type ForceDeploymentStructOutput = [
    string,
    string,
    boolean,
    BigNumber,
    string
  ] & {
    bytecodeHash: string;
    newAddress: string;
    callConstructor: boolean;
    value: BigNumber;
    input: string;
  };
}

export declare namespace IContractDeployer {
  export type AccountInfoStruct = {
    supportedAAVersion: PromiseOrValue<BigNumberish>;
    nonceOrdering: PromiseOrValue<BigNumberish>;
  };

  export type AccountInfoStructOutput = [number, number] & {
    supportedAAVersion: number;
    nonceOrdering: number;
  };
}

export interface ContractDeployerInterface extends utils.Interface {
  functions: {
    "create(bytes32,bytes32,bytes)": FunctionFragment;
    "create2(bytes32,bytes32,bytes)": FunctionFragment;
    "create2Account(bytes32,bytes32,bytes,uint8)": FunctionFragment;
    "createAccount(bytes32,bytes32,bytes,uint8)": FunctionFragment;
    "extendedAccountVersion(address)": FunctionFragment;
    "forceDeployOnAddress((bytes32,address,bool,uint256,bytes),address)": FunctionFragment;
    "forceDeployOnAddresses((bytes32,address,bool,uint256,bytes)[])": FunctionFragment;
    "getAccountInfo(address)": FunctionFragment;
    "getNewAddressCreate(address,uint256)": FunctionFragment;
    "getNewAddressCreate2(address,bytes32,bytes32,bytes)": FunctionFragment;
    "updateAccountVersion(uint8)": FunctionFragment;
    "updateNonceOrdering(uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "create"
      | "create2"
      | "create2Account"
      | "createAccount"
      | "extendedAccountVersion"
      | "forceDeployOnAddress"
      | "forceDeployOnAddresses"
      | "getAccountInfo"
      | "getNewAddressCreate"
      | "getNewAddressCreate2"
      | "updateAccountVersion"
      | "updateNonceOrdering"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "create2",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "create2Account",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createAccount",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "extendedAccountVersion",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "forceDeployOnAddress",
    values: [ContractDeployer.ForceDeploymentStruct, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "forceDeployOnAddresses",
    values: [ContractDeployer.ForceDeploymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccountInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewAddressCreate",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getNewAddressCreate2",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAccountVersion",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateNonceOrdering",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "create2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "create2Account",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendedAccountVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceDeployOnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceDeployOnAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAccountInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewAddressCreate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNewAddressCreate2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAccountVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateNonceOrdering",
    data: BytesLike
  ): Result;

  events: {
    "AccountNonceOrderingUpdated(address,uint8)": EventFragment;
    "AccountVersionUpdated(address,uint8)": EventFragment;
    "ContractDeployed(address,bytes32,address)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AccountNonceOrderingUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AccountVersionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ContractDeployed"): EventFragment;
}

export interface AccountNonceOrderingUpdatedEventObject {
  accountAddress: string;
  nonceOrdering: number;
}
export type AccountNonceOrderingUpdatedEvent = TypedEvent<
  [string, number],
  AccountNonceOrderingUpdatedEventObject
>;

export type AccountNonceOrderingUpdatedEventFilter =
  TypedEventFilter<AccountNonceOrderingUpdatedEvent>;

export interface AccountVersionUpdatedEventObject {
  accountAddress: string;
  aaVersion: number;
}
export type AccountVersionUpdatedEvent = TypedEvent<
  [string, number],
  AccountVersionUpdatedEventObject
>;

export type AccountVersionUpdatedEventFilter =
  TypedEventFilter<AccountVersionUpdatedEvent>;

export interface ContractDeployedEventObject {
  deployerAddress: string;
  bytecodeHash: string;
  contractAddress: string;
}
export type ContractDeployedEvent = TypedEvent<
  [string, string, string],
  ContractDeployedEventObject
>;

export type ContractDeployedEventFilter =
  TypedEventFilter<ContractDeployedEvent>;

export interface ContractDeployer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ContractDeployerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    create(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    create2(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    create2Account(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createAccount(
      arg0: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    extendedAccountVersion(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number]>;

    forceDeployOnAddress(
      _deployment: ContractDeployer.ForceDeploymentStruct,
      _sender: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    forceDeployOnAddresses(
      _deployments: ContractDeployer.ForceDeploymentStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAccountInfo(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [IContractDeployer.AccountInfoStructOutput] & {
        info: IContractDeployer.AccountInfoStructOutput;
      }
    >;

    getNewAddressCreate(
      _sender: PromiseOrValue<string>,
      _senderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    getNewAddressCreate2(
      _sender: PromiseOrValue<string>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { newAddress: string }>;

    updateAccountVersion(
      _version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateNonceOrdering(
      _nonceOrdering: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  create(
    _salt: PromiseOrValue<BytesLike>,
    _bytecodeHash: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  create2(
    _salt: PromiseOrValue<BytesLike>,
    _bytecodeHash: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  create2Account(
    _salt: PromiseOrValue<BytesLike>,
    _bytecodeHash: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    _aaVersion: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createAccount(
    arg0: PromiseOrValue<BytesLike>,
    _bytecodeHash: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    _aaVersion: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  extendedAccountVersion(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<number>;

  forceDeployOnAddress(
    _deployment: ContractDeployer.ForceDeploymentStruct,
    _sender: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  forceDeployOnAddresses(
    _deployments: ContractDeployer.ForceDeploymentStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAccountInfo(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<IContractDeployer.AccountInfoStructOutput>;

  getNewAddressCreate(
    _sender: PromiseOrValue<string>,
    _senderNonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getNewAddressCreate2(
    _sender: PromiseOrValue<string>,
    _bytecodeHash: PromiseOrValue<BytesLike>,
    _salt: PromiseOrValue<BytesLike>,
    _input: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  updateAccountVersion(
    _version: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateNonceOrdering(
    _nonceOrdering: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    create(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    create2(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    create2Account(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    createAccount(
      arg0: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    extendedAccountVersion(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<number>;

    forceDeployOnAddress(
      _deployment: ContractDeployer.ForceDeploymentStruct,
      _sender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    forceDeployOnAddresses(
      _deployments: ContractDeployer.ForceDeploymentStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    getAccountInfo(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<IContractDeployer.AccountInfoStructOutput>;

    getNewAddressCreate(
      _sender: PromiseOrValue<string>,
      _senderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getNewAddressCreate2(
      _sender: PromiseOrValue<string>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    updateAccountVersion(
      _version: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateNonceOrdering(
      _nonceOrdering: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AccountNonceOrderingUpdated(address,uint8)"(
      accountAddress?: PromiseOrValue<string> | null,
      nonceOrdering?: null
    ): AccountNonceOrderingUpdatedEventFilter;
    AccountNonceOrderingUpdated(
      accountAddress?: PromiseOrValue<string> | null,
      nonceOrdering?: null
    ): AccountNonceOrderingUpdatedEventFilter;

    "AccountVersionUpdated(address,uint8)"(
      accountAddress?: PromiseOrValue<string> | null,
      aaVersion?: null
    ): AccountVersionUpdatedEventFilter;
    AccountVersionUpdated(
      accountAddress?: PromiseOrValue<string> | null,
      aaVersion?: null
    ): AccountVersionUpdatedEventFilter;

    "ContractDeployed(address,bytes32,address)"(
      deployerAddress?: PromiseOrValue<string> | null,
      bytecodeHash?: PromiseOrValue<BytesLike> | null,
      contractAddress?: PromiseOrValue<string> | null
    ): ContractDeployedEventFilter;
    ContractDeployed(
      deployerAddress?: PromiseOrValue<string> | null,
      bytecodeHash?: PromiseOrValue<BytesLike> | null,
      contractAddress?: PromiseOrValue<string> | null
    ): ContractDeployedEventFilter;
  };

  estimateGas: {
    create(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    create2(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    create2Account(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createAccount(
      arg0: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    extendedAccountVersion(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    forceDeployOnAddress(
      _deployment: ContractDeployer.ForceDeploymentStruct,
      _sender: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    forceDeployOnAddresses(
      _deployments: ContractDeployer.ForceDeploymentStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAccountInfo(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewAddressCreate(
      _sender: PromiseOrValue<string>,
      _senderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNewAddressCreate2(
      _sender: PromiseOrValue<string>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateAccountVersion(
      _version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateNonceOrdering(
      _nonceOrdering: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    create(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    create2(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    create2Account(
      _salt: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createAccount(
      arg0: PromiseOrValue<BytesLike>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      _aaVersion: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    extendedAccountVersion(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    forceDeployOnAddress(
      _deployment: ContractDeployer.ForceDeploymentStruct,
      _sender: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    forceDeployOnAddresses(
      _deployments: ContractDeployer.ForceDeploymentStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAccountInfo(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewAddressCreate(
      _sender: PromiseOrValue<string>,
      _senderNonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNewAddressCreate2(
      _sender: PromiseOrValue<string>,
      _bytecodeHash: PromiseOrValue<BytesLike>,
      _salt: PromiseOrValue<BytesLike>,
      _input: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateAccountVersion(
      _version: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateNonceOrdering(
      _nonceOrdering: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
