FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /fusion-dance-parade

ADD . /fusion-dance-parade

RUN yarn --ignore-scripts && env NODE_ENV=production yarn build

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

COPY --from=build /fusion-dance-parade/out /dist

CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]